# Generated by Django 2.2.6 on 2019-11-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('name', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
