# Generated by Django 2.2.6 on 2020-03-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_of_user',
            name='userId',
            field=models.IntegerField(default=1),
        ),
    ]
