# Generated by Django 2.2.6 on 2020-03-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20200315_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_of_user',
            name='userImg',
            field=models.FileField(upload_to='images/avatar/'),
        ),
    ]
