# Generated by Django 2.2.6 on 2020-03-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20200315_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_of_user',
            name='userImg',
            field=models.FileField(default='images/avatar/no-ava.png', upload_to='images/avatar/'),
        ),
    ]
