# Generated by Django 2.2.6 on 2020-03-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20200315_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL_for_reset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeURL', models.IntegerField()),
                ('userId', models.IntegerField(default=1)),
            ],
        ),
    ]
