# Generated by Django 2.2.3 on 2020-04-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_url_for_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_for_reset',
            name='codeURL',
            field=models.TextField(),
        ),
    ]
