# Generated by Django 3.0.2 on 2020-03-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_goods',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
