# Generated by Django 2.2.6 on 2020-02-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_goods',
            name='description',
            field=models.TextField(default='description empty'),
        ),
    ]
