# Generated by Django 2.2.3 on 2020-02-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_about_goods_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_of_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('goodId', models.IntegerField()),
            ],
        ),
    ]
