# Generated by Django 3.0.2 on 2020-03-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0003_about_goods_suck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_goods',
            name='suck',
        ),
    ]
