# Generated by Django 2.2.6 on 2020-03-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0004_remove_about_goods_suck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_goods',
            name='rating',
            field=models.TextField(default='0.00'),
        ),
    ]
