# Generated by Django 2.2.3 on 2020-04-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0005_auto_20200315_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_of_user',
            name='checked',
            field=models.IntegerField(default=1),
        ),
    ]
