# Generated by Django 2.2.3 on 2020-04-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0006_goods_of_user_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_of_user',
            name='checked',
            field=models.IntegerField(default=0),
        ),
    ]
