# Generated by Django 2.2.6 on 2020-03-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('goodId', models.IntegerField()),
                ('count', models.IntegerField()),
                ('result', models.IntegerField(default=0)),
                ('numberOfOrder', models.TextField()),
                ('status', models.TextField(default='Отправлено')),
            ],
        ),
    ]
