# Generated by Django 3.0.2 on 2020-03-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
