# Generated by Django 2.2.6 on 2020-03-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.TextField(default='0.00'),
        ),
    ]
